In [5]:
import pandas as pd

In [6]:
temp = pd.read_csv("../Bases/Base de Dados NOAA.csv")
# samp = pd.read_csv("../Bases/samp-2003.csv", nrows=1000)

In [7]:
temp.info()

<class 'pandas.DataFrame'>
RangeIndex: 924 entries, 0 to 923
Data columns (total 2 columns):
 #   Column                                                                           Non-Null Count  Dtype
---  ------                                                                           --------------  -----
 0   Date                                                                             924 non-null    str
 1     ONI from CPC  missing value -99.9 https://psl.noaa.gov/data/timeseries/month/  924 non-null    float64
dtypes: float64(1), str(1)
memory usage: 14.6 KB

In [8]:
temp

,Date,ONI from CPC missing value -99.9 https://psl.noaa.gov/data/timeseries/month/
0,1950-01-01,-1.53
1,1950-02-01,-1.34
2,1950-03-01,-1.16
3,1950-04-01,-1.18
4,1950-05-01,-1.07
...,...,...
919,2026-08-01,-9999.00
920,2026-09-01,-9999.00
921,2026-10-01,-9999.00
922,2026-11-01,-9999.00
923,2026-12-01,-9999.00

In [9]:
temp.rename(columns={'  ONI from CPC  missing value -99.9 https://psl.noaa.gov/data/timeseries/month/' : 'Temperatura'},inplace=True)

In [10]:
temp.loc[(temp['Date'] > "2003-01-01") & (temp['Date'] < "2004-01-01")]

           Date  Temperatura
637  2003-02-01         0.63
638  2003-03-01         0.38
639  2003-04-01        -0.04
640  2003-05-01        -0.26
641  2003-06-01        -0.16
642  2003-07-01         0.08
643  2003-08-01         0.21
644  2003-09-01         0.26
645  2003-10-01         0.29
646  2003-11-01         0.35
647  2003-12-01         0.35

próximos passos: 
                <br>Verificar em qual temperatura está ocorrendo tais oscilações;<br>
                 Verificar em quais anos o el-ninõ aconteceu para que possamos ser mais acertivos;<br>
                 Comparar os datasets;<br>
                 Pegar a API e jogar em um excel;<br>