Sites para referências:


"https://medium.com/@laiosoares6/como-ler-arquivos-de-diferentes-formatos-e-transformar-em-dataframes-usando-pandas-8c4f4a360f15"

In [40]:
import pandas as pd
from pathlib import Path
import openpyxl as xlxs

OPEN-METEO

In [41]:
caminho = Path(r"../../data/bronze/Open-Meteo - Clima.json")
aux = pd.read_json(caminho)

In [42]:
open_meteo = pd.DataFrame(aux)
open_meteo

,_fonte,_endpoint,_extraido_em,_load_id,dados
latitude,Open-Meteo,https://archive-api.open-meteo.com/v1/archive,2026-10-02T20:17:52+00:00,NaN,-29.982426
longitude,Open-Meteo,https://archive-api.open-meteo.com/v1/archive,2026-10-02T20:17:52+00:00,NaN,-51.188812
generationtime_ms,Open-Meteo,https://archive-api.open-meteo.com/v1/archive,2026-10-02T20:17:52+00:00,NaN,332.758904
utc_offset_seconds,Open-Meteo,https://archive-api.open-meteo.com/v1/archive,2026-10-02T20:17:52+00:00,NaN,-10800
timezone,Open-Meteo,https://archive-api.open-meteo.com/v1/archive,2026-10-02T20:17:52+00:00,NaN,America/Sao_Paulo
timezone_abbreviation,Open-Meteo,https://archive-api.open-meteo.com/v1/archive,2026-10-02T20:17:52+00:00,NaN,GMT-3
elevation,Open-Meteo,https://archive-api.open-meteo.com/v1/archive,2026-10-02T20:17:52+00:00,NaN,30.0
daily_units,Open-Meteo,https://archive-api.open-meteo.com/v1/archive,2026-10-02T20:17:52+00:00,NaN,"{'time': 'iso8601', 'temperature_2m_max': '°C'..."
daily,Open-Meteo,https://archive-api.open-meteo.com/v1/archive,2026-10-02T20:17:52+00:00,NaN,"{'time': ['2015-01-01', '2015-01-02', '2015-01..."

NOAA

In [43]:
caminho_Oni = Path("../../data/bronze/noaa_oni/oni_1950_presente.txt")
teste = pd.read_table(caminho_Oni)

In [44]:
noaa = pd.DataFrame(teste)
noaa

                                    1950         2026
0    1950  -1.53  -1.34  -1.16  -1.18  -1.07  -0.8...
1    1951  -0.82  -0.54  -0.17   0.18   0.36   0.5...
2    1952   0.53   0.37   0.34   0.29   0.20   0.0...
3    1953   0.40   0.60   0.63   0.66   0.75   0.7...
4    1954   0.76   0.47  -0.05  -0.41  -0.54  -0.5...
..                                                ...
80    From https://www.cpc.ncep.noaa.gov/data/indi...
81                As of 08/4/2026, uses NOAA ERSST V6
82    represents 3 month running mean of ERSST.v6 SST
83                  anomalies in the Niño 3.4 region
84                              (5N-5oS, 120o-170oW)]

[85 rows x 1 columns]

EPE

In [47]:
caminho_epe = Path("../../data/bronze/epe_consumo/consumo_mensal_historico.xlsx")
epe = pd.read_excel(caminho_epe)
epe

,Data,DataExcel,Regiao,Sistema,Classe,TipoConsumidor,Consumo,Consumidores,DataVersao
0,20260801,2026-08-01,Centro-Oeste,SUDESTE / CENTRO - OESTE,Comercial,Cativo,398821.094,505444,2026-09-18
1,20260801,2026-08-01,Centro-Oeste,SUDESTE / CENTRO - OESTE,Comercial,Livre,308143.745,4213,2026-09-18
2,20260801,2026-08-01,Centro-Oeste,SUDESTE / CENTRO - OESTE,Industrial,Cativo,58522.693,30064,2026-09-18
3,20260801,2026-08-01,Centro-Oeste,SUDESTE / CENTRO - OESTE,Industrial,Livre,967962.423,1579,2026-09-18
4,20260801,2026-08-01,Centro-Oeste,SUDESTE / CENTRO - OESTE,Outros,Cativo,286743.278,64817,2026-09-18
...,...,...,...,...,...,...,...,...,...
18723,20040101,2004-01-01,Sul,SUL,Industrial,Cativo,1464696.468,159190,2026-09-18
18724,20040101,2004-01-01,Sul,SUL,Industrial,Livre,346283.691,42,2026-09-18
18725,20040101,2004-01-01,Sul,SUL,Outros,Cativo,373249.407,84291,2026-09-18
18726,20040101,2004-01-01,Sul,SUL,Residencial,Cativo,1132506.000,6762504,2026-09-18
18727,20040101,2004-01-01,Sul,SUL,Rural,Cativo,489375.701,814350,2026-09-18